### ISSUE TITLE
Tile cannot extend outside image

### ISSUE THREAD

**Issue by umang-kagathara** [Galaxy1036/Dumpsc#1]
Hello, 

I am getting this error.
```
$ python Dumpsc.py info_hogrider_tex.sc
[*] Processing info_hogrider_tex.sc
fileType: 83, fileSize: 67, subType: 1, width: 0, height: 4096
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\PIL\ImageFile.py", line 498, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Dumpsc.py", line 156, in <module>
    process_sc(basename, f.read(), path, args.decompress)
  File "Dumpsc.py", line 132, in process_sc
    img.save(path + baseName + ('_' * picCount) + '.png', 'PNG')
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\PIL\Image.py", line 2084, in save
    save_handler(self, fp, filename)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\PIL\PngImagePlugin.py", line 910, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\PIL\ImageFile.py", line 506, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image

```

**Comment by Galaxy1036** [comment]
The file might be compressed try to re-run the script with the `-d` option
